use BDDOP
Declare @delay decimal
set @delay = 0.1
SELECT * FROM (
SELECT DISTINCT *,
CASE
WHEN CONVERT(DATE, [INICIOAGENDAMENTO]) < CONVERT(DATE, GETDATE()) THEN 'ULTRAPASSADO' 
WHEN CONVERT(DATE, [INICIOAGENDAMENTO]) = CONVERT(DATE, GETDATE()) THEN 'DIA ATUAL' 
WHEN CONVERT(DATE, [INICIOAGENDAMENTO]) = CONVERT(DATE, GETDATE() + 1) THEN 'D + 1' 
WHEN CONVERT(DATE, [INICIOAGENDAMENTO]) = CONVERT(DATE, GETDATE() + 2) THEN 'D + 2' 
WHEN CONVERT(DATE, [INICIOAGENDAMENTO]) = CONVERT(DATE, GETDATE() + 3) THEN 'D + 3' 
WHEN CONVERT(DATE, [INICIOAGENDAMENTO]) = CONVERT(DATE, GETDATE() + 4) THEN 'ENTRE 4 A 7 DIAS' 
WHEN CONVERT(DATE, [INICIOAGENDAMENTO]) = CONVERT(DATE, GETDATE() + 5) THEN 'ENTRE 4 A 7 DIAS' 
WHEN CONVERT(DATE, [INICIOAGENDAMENTO]) = CONVERT(DATE, GETDATE() + 6) THEN 'ENTRE 4 A 7 DIAS' 
WHEN CONVERT(DATE, [INICIOAGENDAMENTO]) = CONVERT(DATE, GETDATE() + 7) THEN 'ENTRE 4 A 7 DIAS' 
WHEN CONVERT(DATE, [INICIOAGENDAMENTO]) > CONVERT(DATE, GETDATE() + 7) THEN 'MAIOR 7 DIAS' 
ELSE 'SEM AGENDAMENTO' END AS FAIXA_AGENDAMENTO,
CASE
WHEN DATEDIFF(DAY, DATAABERTURABA, GETDATE() - 0.4) IS NULL THEN 'COM PENDENCIA'
WHEN DATEDIFF(DAY, DATAABERTURABA, GETDATE() - 0.4) >= '0' AND DATEDIFF(DAY, DATAABERTURABA, GETDATE() - 0.4) <= '5' THEN '0-5 DIAS' 
WHEN DATEDIFF(DAY, DATAABERTURABA, GETDATE() - 0.4) >= '6' AND DATEDIFF(DAY, DATAABERTURABA, GETDATE() - 0.4) <= '11' THEN '6-11 DIAS' 
WHEN DATEDIFF(DAY, DATAABERTURABA, GETDATE() - 0.4) >= '11' AND DATEDIFF(DAY, DATAABERTURABA, GETDATE() - 0.4) <= '21' THEN '11-21 DIAS' 
WHEN DATEDIFF(DAY, DATAABERTURABA, GETDATE() - 0.4) >= '21' AND DATEDIFF(DAY, DATAABERTURABA, GETDATE() - 0.4) <= '30' THEN '21-30 DIAS' 
WHEN DATEDIFF(DAY, DATAABERTURABA, GETDATE() - 0.4) > '30' THEN 'ACIMA DE 30 DIAS' 
END AS FAIXA_AGING_POSTO_CLICK,
CASE
WHEN DATEDIFF(DAY, DATAABERTURABA, GETDATE() - 0.4) IS NULL THEN 'COM PENDENCIA' 
ELSE CONVERT(VARCHAR, DATEDIFF(DAY, DATAABERTURABA, GETDATE() - 0.4)) END AS TEMPO_POSTO_CLICK
FROM
(SELECT TABELA_BOV.*,TBL_ULTIMA_PEND_CONHECIDA.CODIGO_PENDENCIA,TBL_ULTIMA_PEND_CONHECIDA.DATA_ABERTURA_ULTIMA_PENDENCIA_CONHECIDA,CLICK.INICIOEXECUCAO,CLICK.INICIOAGENDAMENTO,CLICK.DATAABERTURABA FROM (
SELECT 'SIM' AS V_TAL, MACROATIVIDADE, 
CASE WHEN COD_RELACIONAMENTO_CLIENTE = 'VELOX' THEN 'PERIMETRO NAO' 
ELSE 'PERIMETRO SIM' END AS PERIMETRO
, UF, SIGLA_LOCALIDADE, SIGLA_GRA, SIGLA_ESTACAO, NUM_DOCUMENTO, DATA_ABERTURA_PRIMEIRA, 
       DATA_ABERTURA, DATA_PROMESSA, COD_PENDENCIA PENDENCIA_BOV_N_CONSIDERAR, NUM_MICRO_AREA, CPF_CNPJ_CLIENTE, TIPO_INSTALACAO, INICIO_EXECUCAO, PDV_SAP, 
       CASE
		WHEN TIPO_INSTALACAO = 'N' THEN 'INST' ELSE 'MIG' 
	   END AS [REPORT TIPO], 
       CASE 
		WHEN PDV_SAP = '1044817' THEN 'MIG SUPORTE TECNICO' ELSE 'DEMAIS CANAIS' 
	   END AS [FLAG PDV],
		CASE 
		WHEN DATEDIFF(DAY, DATA_ABERTURA_PRIMEIRA, DATA_ATUALIZACAO -@delay) IS NULL THEN 'SEM DATA DE ABERTURA' 
		WHEN DATEDIFF(DAY, DATA_ABERTURA_PRIMEIRA, DATA_ATUALIZACAO -@delay) >= '0' AND DATEDIFF(DAY, DATA_ABERTURA_PRIMEIRA, DATA_ATUALIZACAO -@delay) <= '4' THEN '0-4 DIAS'
		WHEN DATEDIFF(DAY, DATA_ABERTURA_PRIMEIRA, DATA_ATUALIZACAO -@delay) > '4' AND DATEDIFF(DAY, DATA_ABERTURA_PRIMEIRA, DATA_ATUALIZACAO -@delay) <= '7' THEN '5-7 DIAS' 
		WHEN DATEDIFF(DAY, DATA_ABERTURA_PRIMEIRA, DATA_ATUALIZACAO -@delay) > '7' AND DATEDIFF(DAY, DATA_ABERTURA_PRIMEIRA, DATA_ATUALIZACAO -@delay) <= '12' THEN '8-12 DIAS' 
		WHEN DATEDIFF(DAY, DATA_ABERTURA_PRIMEIRA, DATA_ATUALIZACAO -@delay) > '12' AND DATEDIFF(DAY, DATA_ABERTURA_PRIMEIRA, DATA_ATUALIZACAO -@delay) <= '20' THEN '13-20 DIAS' 
		WHEN DATEDIFF(DAY, DATA_ABERTURA_PRIMEIRA, DATA_ATUALIZACAO -@delay) > '20' AND DATEDIFF(DAY, DATA_ABERTURA_PRIMEIRA, DATA_ATUALIZACAO -@delay) <= '30' THEN '21-30 DIAS' 
		WHEN DATEDIFF(DAY, DATA_ABERTURA_PRIMEIRA, DATA_ATUALIZACAO -@delay) > '30' THEN 'ACIMA DE 30 DIAS' 
	   END AS FAIXA_AGING_PEDIDO, 
       DATEDIFF(DAY, DATA_ABERTURA_PRIMEIRA, GETDATE() - 0.4) AS AGING_DAY_CLIENTE,
	   DATEDIFF(HOUR, DATA_ABERTURA_PRIMEIRA, GETDATE() - 0.4)AS AGING_HOUR_CLIENTE,
	   TERMINAL, DDD, TELEFONE
FROM SIEBEL_SERVICO_ABERTO_FTTH_BOV
WHERE  (DATA_ATUALIZACAO = (SELECT  MAX(DATA_ATUALIZACAO) AS Expr1
FROM SIEBEL_SERVICO_ABERTO_FTTH_BOV)) AND (MACROATIVIDADE = 'INST') AND (FLAG_CADEIA = 'S')) 
TABELA_BOV LEFT JOIN 
(SELECT NUMERO_PEDIDO,DATA_ABERTURA_ULTIMA_PENDENCIA_CONHECIDA,CODIGO_PENDENCIA
FROM SIDARA_OMR_TRAMITACAO_FTTH AS TBL_TRAMITE
INNER JOIN (
SELECT NUMERO_PEDIDO AS PEDIDO, MAX(DATA_ABERTURA_ATIVIDADE) AS DATA_ABERTURA_ULTIMA_PENDENCIA_CONHECIDA
from SIDARA_OMR_TRAMITACAO_FTTH 
where CODIGO_PENDENCIA like '7%' 
AND NUMERO_PEDIDO IN 
(SELECT NUM_DOCUMENTO FROM SIEBEL_SERVICO_ABERTO_FTTH_BOV
WHERE DATA_ATUALIZACAO = (SELECT MAX(DATA_ATUALIZACAO) AS Expr1
FROM SIEBEL_SERVICO_ABERTO_FTTH_BOV) AND MACROATIVIDADE = 'INST' AND FLAG_CADEIA = 'S')
GROUP BY NUMERO_PEDIDO
) AS TBL_DT
ON TBL_DT.PEDIDO = TBL_TRAMITE.NUMERO_PEDIDO 
AND TBL_TRAMITE.DATA_ABERTURA_ATIVIDADE = TBL_DT.DATA_ABERTURA_ULTIMA_PENDENCIA_CONHECIDA
)TBL_ULTIMA_PEND_CONHECIDA 
ON TABELA_BOV.NUM_DOCUMENTO = TBL_ULTIMA_PEND_CONHECIDA.NUMERO_PEDIDO
LEFT JOIN (SELECT * FROM CLICK_ABERTAS
WHERE SKILLS LIKE '%FTTH%' AND ATIVIDADE <> 'INSTALAR JUMPER FTTH' AND DATAINDICADOR =
(SELECT MAX(DATAINDICADOR) FROM CLICK_ABERTAS)
)CLICK ON TABELA_BOV.NUM_DOCUMENTO = CLICK.DOCUMENTOASSOCIADO
)ART7) TBL1 LEFT JOIN(
SELECT COUNT(*) QTE_TRAMITACAO,NUMERO_PEDIDO,CODIGO_PENDENCIA COD_PENDENCIA_QTE_TRAMITACAO
FROM SIDARA_OMR_TRAMITACAO_FTTH
where CODIGO_PENDENCIA like '7%' AND TIPO_OS='INSTALACAO'
GROUP BY NUMERO_PEDIDO,CODIGO_PENDENCIA
) TBL2 ON TBL1.NUM_DOCUMENTO = TBL2.NUMERO_PEDIDO LEFT JOIN (
SELECT COUNT(*) TOTAL_TRAMITACAO,NUMERO_PEDIDO AS NUMERO_PEDIDO_1
FROM SIDARA_OMR_TRAMITACAO_FTTH
where CODIGO_PENDENCIA like'7%' AND CODIGO_PENDENCIA <> 7029 AND TIPO_OS='INSTALACAO'
AND CODIGO_PENDENCIA <> 7033  AND CODIGO_PENDENCIA <> 7039
GROUP BY NUMERO_PEDIDO) TBL3 ON TBL1.NUM_DOCUMENTO = TBL3.NUMERO_PEDIDO_1
WHERE CODIGO_PENDENCIA like '7%' OR  CODIGO_PENDENCIA IS NULL
order by NUM_DOCUMENTO ASC